// Generated by https://quicktype.io

export interface IloginResponse {
  message: string;
  user: User;
  Access_token: string;
}

export interface User {
  email: string;
  username: string;
  fullname: string;
}
// Generated by https://quicktype.io

export interface IloginBody {
  email: string;
  password: string;
}
