// Generated by https://quicktype.io

export interface IloginResponse {
  message: string;
  user: User;
  Access_token: string;
}

export interface User {
  id: number;
  email: string;
  username: string;
  fullname: string;
}
// Generated by https://quicktype.io

export interface IloginBody {
  email: string;
  password: string;
}
export enum Role {
  ADMIN = "ADMIN",
  USER = "USER",
  Teacher = "Teacher",
}
