// Generated by https://quicktype.io

// export interface IRegisterResponse {
//   user: User[];
//   message: string;
// }

export interface IRegisterResponse {
  id: number;
  fullName: string;
  username: string;
  email: string;
  phoneNumber: string;
  password: string;
  confirmpassword: string;
  createdAt: Date;
  updatedAt: Date;
}
// Generated by https://quicktype.io

export interface IRegisterBody {
  username: string;
  email: string;
  password: string;
  fullName: string;
  phoneNumber: string;
}

export interface AttendancePayload {
  studentId: string;
  present: boolean;
  remark: string;
}
